# Generated by Django 3.1.5 on 2021-03-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(help_text='Please enter valid password.', max_length=128, verbose_name='password')),
                ('select_courses', models.CharField(choices=[('DEV', 'devops'), ('PY', 'python'), ('DJ', 'django'), ('RJ', 'react_js'), ('JS', 'javascript')], default='DEV', max_length=10)),
            ],
        ),
    ]
