# Generated by Django 3.1.5 on 2021-03-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='select_courses',
            field=models.CharField(blank=True, choices=[('DEV', 'devops'), ('PY', 'python'), ('DJ', 'django'), ('RJ', 'react_js'), ('JS', 'javascript')], default='DEV', max_length=10, null=True),
        ),
    ]
